/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AppVendasRouteImport } from './routes/_app/vendas'
import { Route as AppStatusRouteImport } from './routes/_app/status'
import { Route as AppRepresentantesRouteImport } from './routes/_app/representantes'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppRegistroCampoRouteImport } from './routes/_app/registro-campo'
import { Route as AppPropostasRouteImport } from './routes/_app/propostas'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppPreferenciasRouteImport } from './routes/_app/preferencias'
import { Route as AppPlanejamentoVisitasRouteImport } from './routes/_app/planejamento-visitas'
import { Route as AppPlanejamentoRouteImport } from './routes/_app/planejamento'
import { Route as AppPedidosRouteImport } from './routes/_app/pedidos'
import { Route as AppOportunidadesRouteImport } from './routes/_app/oportunidades'
import { Route as AppMetasRouteImport } from './routes/_app/metas'
import { Route as AppMapaRouteImport } from './routes/_app/mapa'
import { Route as AppInteligenciaRouteImport } from './routes/_app/inteligencia'
import { Route as AppImportacaoRouteImport } from './routes/_app/importacao'
import { Route as AppIaInsightsRouteImport } from './routes/_app/ia-insights'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppAutomacoesRouteImport } from './routes/_app/automacoes'
import { Route as AppAtividadesRouteImport } from './routes/_app/atividades'
import { Route as AppAppRepresentanteRouteImport } from './routes/_app/app-representante'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAlertasRouteImport } from './routes/_app/alertas'
import { Route as AppRepresentantesIdRouteImport } from './routes/_app/representantes.$id'
import { Route as AppAlertasConfigRouteImport } from './routes/_app/alertas.config'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksWhatsappRouteImport } from './routes/api/public/hooks/whatsapp'
import { Route as ApiPublicHooksSendWelcomeRouteImport } from './routes/api/public/hooks/send-welcome'
import { Route as ApiPublicHooksRunAlertsRouteImport } from './routes/api/public/hooks/run-alerts'
import { Route as ApiPublicHooksDailyDigestRouteImport } from './routes/api/public/hooks/daily-digest'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppRepresentantesRoute = AppRepresentantesRouteImport.update({
  id: '/representantes',
  path: '/representantes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistroCampoRoute = AppRegistroCampoRouteImport.update({
  id: '/registro-campo',
  path: '/registro-campo',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferenciasRoute = AppPreferenciasRouteImport.update({
  id: '/preferencias',
  path: '/preferencias',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanejamentoVisitasRoute = AppPlanejamentoVisitasRouteImport.update({
  id: '/planejamento-visitas',
  path: '/planejamento-visitas',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanejamentoRoute = AppPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesRoute = AppOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaRoute = AppInteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => AppRoute,
} as any)
const AppImportacaoRoute = AppImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AppRoute,
} as any)
const AppIaInsightsRoute = AppIaInsightsRouteImport.update({
  id: '/ia-insights',
  path: '/ia-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadesRoute = AppAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRepresentanteRoute = AppAppRepresentanteRouteImport.update({
  id: '/app-representante',
  path: '/app-representante',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppRepresentantesIdRoute = AppRepresentantesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRepresentantesRoute,
} as any)
const AppAlertasConfigRoute = AppAlertasConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppAlertasRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappRoute = ApiPublicHooksWhatsappRouteImport.update({
  id: '/api/public/hooks/whatsapp',
  path: '/api/public/hooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendWelcomeRoute =
  ApiPublicHooksSendWelcomeRouteImport.update({
    id: '/api/public/hooks/send-welcome',
    path: '/api/public/hooks/send-welcome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunAlertsRoute = ApiPublicHooksRunAlertsRouteImport.update({
  id: '/api/public/hooks/run-alerts',
  path: '/api/public/hooks/run-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyDigestRoute =
  ApiPublicHooksDailyDigestRouteImport.update({
    id: '/api/public/hooks/daily-digest',
    path: '/api/public/hooks/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alertas': typeof AppAlertasRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/app-representante': typeof AppAppRepresentanteRoute
  '/atividades': typeof AppAtividadesRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/ia-insights': typeof AppIaInsightsRoute
  '/importacao': typeof AppImportacaoRoute
  '/inteligencia': typeof AppInteligenciaRoute
  '/mapa': typeof AppMapaRoute
  '/metas': typeof AppMetasRoute
  '/oportunidades': typeof AppOportunidadesRoute
  '/pedidos': typeof AppPedidosRoute
  '/planejamento': typeof AppPlanejamentoRoute
  '/planejamento-visitas': typeof AppPlanejamentoVisitasRoute
  '/preferencias': typeof AppPreferenciasRoute
  '/produtos': typeof AppProdutosRoute
  '/propostas': typeof AppPropostasRoute
  '/registro-campo': typeof AppRegistroCampoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/representantes': typeof AppRepresentantesRouteWithChildren
  '/status': typeof AppStatusRoute
  '/vendas': typeof AppVendasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/alertas/config': typeof AppAlertasConfigRoute
  '/representantes/$id': typeof AppRepresentantesIdRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/run-alerts': typeof ApiPublicHooksRunAlertsRoute
  '/api/public/hooks/send-welcome': typeof ApiPublicHooksSendWelcomeRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alertas': typeof AppAlertasRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/app-representante': typeof AppAppRepresentanteRoute
  '/atividades': typeof AppAtividadesRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/ia-insights': typeof AppIaInsightsRoute
  '/importacao': typeof AppImportacaoRoute
  '/inteligencia': typeof AppInteligenciaRoute
  '/mapa': typeof AppMapaRoute
  '/metas': typeof AppMetasRoute
  '/oportunidades': typeof AppOportunidadesRoute
  '/pedidos': typeof AppPedidosRoute
  '/planejamento': typeof AppPlanejamentoRoute
  '/planejamento-visitas': typeof AppPlanejamentoVisitasRoute
  '/preferencias': typeof AppPreferenciasRoute
  '/produtos': typeof AppProdutosRoute
  '/propostas': typeof AppPropostasRoute
  '/registro-campo': typeof AppRegistroCampoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/representantes': typeof AppRepresentantesRouteWithChildren
  '/status': typeof AppStatusRoute
  '/vendas': typeof AppVendasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/alertas/config': typeof AppAlertasConfigRoute
  '/representantes/$id': typeof AppRepresentantesIdRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/run-alerts': typeof ApiPublicHooksRunAlertsRoute
  '/api/public/hooks/send-welcome': typeof ApiPublicHooksSendWelcomeRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/alertas': typeof AppAlertasRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/app-representante': typeof AppAppRepresentanteRoute
  '/_app/atividades': typeof AppAtividadesRoute
  '/_app/automacoes': typeof AppAutomacoesRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ia-insights': typeof AppIaInsightsRoute
  '/_app/importacao': typeof AppImportacaoRoute
  '/_app/inteligencia': typeof AppInteligenciaRoute
  '/_app/mapa': typeof AppMapaRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/oportunidades': typeof AppOportunidadesRoute
  '/_app/pedidos': typeof AppPedidosRoute
  '/_app/planejamento': typeof AppPlanejamentoRoute
  '/_app/planejamento-visitas': typeof AppPlanejamentoVisitasRoute
  '/_app/preferencias': typeof AppPreferenciasRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/propostas': typeof AppPropostasRoute
  '/_app/registro-campo': typeof AppRegistroCampoRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/representantes': typeof AppRepresentantesRouteWithChildren
  '/_app/status': typeof AppStatusRoute
  '/_app/vendas': typeof AppVendasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_app/alertas/config': typeof AppAlertasConfigRoute
  '/_app/representantes/$id': typeof AppRepresentantesIdRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/run-alerts': typeof ApiPublicHooksRunAlertsRoute
  '/api/public/hooks/send-welcome': typeof ApiPublicHooksSendWelcomeRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/planos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/alertas'
    | '/analytics'
    | '/app-representante'
    | '/atividades'
    | '/automacoes'
    | '/clientes'
    | '/dashboard'
    | '/ia-insights'
    | '/importacao'
    | '/inteligencia'
    | '/mapa'
    | '/metas'
    | '/oportunidades'
    | '/pedidos'
    | '/planejamento'
    | '/planejamento-visitas'
    | '/preferencias'
    | '/produtos'
    | '/propostas'
    | '/registro-campo'
    | '/relatorios'
    | '/representantes'
    | '/status'
    | '/vendas'
    | '/checkout/return'
    | '/alertas/config'
    | '/representantes/$id'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/run-alerts'
    | '/api/public/hooks/send-welcome'
    | '/api/public/hooks/whatsapp'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/planos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/alertas'
    | '/analytics'
    | '/app-representante'
    | '/atividades'
    | '/automacoes'
    | '/clientes'
    | '/dashboard'
    | '/ia-insights'
    | '/importacao'
    | '/inteligencia'
    | '/mapa'
    | '/metas'
    | '/oportunidades'
    | '/pedidos'
    | '/planejamento'
    | '/planejamento-visitas'
    | '/preferencias'
    | '/produtos'
    | '/propostas'
    | '/registro-campo'
    | '/relatorios'
    | '/representantes'
    | '/status'
    | '/vendas'
    | '/checkout/return'
    | '/alertas/config'
    | '/representantes/$id'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/run-alerts'
    | '/api/public/hooks/send-welcome'
    | '/api/public/hooks/whatsapp'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/diagnostics'
    | '/login'
    | '/planos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_app/alertas'
    | '/_app/analytics'
    | '/_app/app-representante'
    | '/_app/atividades'
    | '/_app/automacoes'
    | '/_app/clientes'
    | '/_app/dashboard'
    | '/_app/ia-insights'
    | '/_app/importacao'
    | '/_app/inteligencia'
    | '/_app/mapa'
    | '/_app/metas'
    | '/_app/oportunidades'
    | '/_app/pedidos'
    | '/_app/planejamento'
    | '/_app/planejamento-visitas'
    | '/_app/preferencias'
    | '/_app/produtos'
    | '/_app/propostas'
    | '/_app/registro-campo'
    | '/_app/relatorios'
    | '/_app/representantes'
    | '/_app/status'
    | '/_app/vendas'
    | '/checkout/return'
    | '/_app/alertas/config'
    | '/_app/representantes/$id'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/run-alerts'
    | '/api/public/hooks/send-welcome'
    | '/api/public/hooks/whatsapp'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DiagnosticsRoute: typeof DiagnosticsRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicHooksDailyDigestRoute: typeof ApiPublicHooksDailyDigestRoute
  ApiPublicHooksRunAlertsRoute: typeof ApiPublicHooksRunAlertsRoute
  ApiPublicHooksSendWelcomeRoute: typeof ApiPublicHooksSendWelcomeRoute
  ApiPublicHooksWhatsappRoute: typeof ApiPublicHooksWhatsappRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/representantes': {
      id: '/_app/representantes'
      path: '/representantes'
      fullPath: '/representantes'
      preLoaderRoute: typeof AppRepresentantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registro-campo': {
      id: '/_app/registro-campo'
      path: '/registro-campo'
      fullPath: '/registro-campo'
      preLoaderRoute: typeof AppRegistroCampoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/propostas': {
      id: '/_app/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preferencias': {
      id: '/_app/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof AppPreferenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planejamento-visitas': {
      id: '/_app/planejamento-visitas'
      path: '/planejamento-visitas'
      fullPath: '/planejamento-visitas'
      preLoaderRoute: typeof AppPlanejamentoVisitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planejamento': {
      id: '/_app/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AppPlanejamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oportunidades': {
      id: '/_app/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AppOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa': {
      id: '/_app/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inteligencia': {
      id: '/_app/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof AppInteligenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importacao': {
      id: '/_app/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AppImportacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia-insights': {
      id: '/_app/ia-insights'
      path: '/ia-insights'
      fullPath: '/ia-insights'
      preLoaderRoute: typeof AppIaInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automacoes': {
      id: '/_app/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atividades': {
      id: '/_app/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AppAtividadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app-representante': {
      id: '/_app/app-representante'
      path: '/app-representante'
      fullPath: '/app-representante'
      preLoaderRoute: typeof AppAppRepresentanteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/representantes/$id': {
      id: '/_app/representantes/$id'
      path: '/$id'
      fullPath: '/representantes/$id'
      preLoaderRoute: typeof AppRepresentantesIdRouteImport
      parentRoute: typeof AppRepresentantesRoute
    }
    '/_app/alertas/config': {
      id: '/_app/alertas/config'
      path: '/config'
      fullPath: '/alertas/config'
      preLoaderRoute: typeof AppAlertasConfigRouteImport
      parentRoute: typeof AppAlertasRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp': {
      id: '/api/public/hooks/whatsapp'
      path: '/api/public/hooks/whatsapp'
      fullPath: '/api/public/hooks/whatsapp'
      preLoaderRoute: typeof ApiPublicHooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-welcome': {
      id: '/api/public/hooks/send-welcome'
      path: '/api/public/hooks/send-welcome'
      fullPath: '/api/public/hooks/send-welcome'
      preLoaderRoute: typeof ApiPublicHooksSendWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-alerts': {
      id: '/api/public/hooks/run-alerts'
      path: '/api/public/hooks/run-alerts'
      fullPath: '/api/public/hooks/run-alerts'
      preLoaderRoute: typeof ApiPublicHooksRunAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-digest': {
      id: '/api/public/hooks/daily-digest'
      path: '/api/public/hooks/daily-digest'
      fullPath: '/api/public/hooks/daily-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAlertasRouteChildren {
  AppAlertasConfigRoute: typeof AppAlertasConfigRoute
}

const AppAlertasRouteChildren: AppAlertasRouteChildren = {
  AppAlertasConfigRoute: AppAlertasConfigRoute,
}

const AppAlertasRouteWithChildren = AppAlertasRoute._addFileChildren(
  AppAlertasRouteChildren,
)

interface AppRepresentantesRouteChildren {
  AppRepresentantesIdRoute: typeof AppRepresentantesIdRoute
}

const AppRepresentantesRouteChildren: AppRepresentantesRouteChildren = {
  AppRepresentantesIdRoute: AppRepresentantesIdRoute,
}

const AppRepresentantesRouteWithChildren =
  AppRepresentantesRoute._addFileChildren(AppRepresentantesRouteChildren)

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppRepresentanteRoute: typeof AppAppRepresentanteRoute
  AppAtividadesRoute: typeof AppAtividadesRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIaInsightsRoute: typeof AppIaInsightsRoute
  AppImportacaoRoute: typeof AppImportacaoRoute
  AppInteligenciaRoute: typeof AppInteligenciaRoute
  AppMapaRoute: typeof AppMapaRoute
  AppMetasRoute: typeof AppMetasRoute
  AppOportunidadesRoute: typeof AppOportunidadesRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppPlanejamentoRoute: typeof AppPlanejamentoRoute
  AppPlanejamentoVisitasRoute: typeof AppPlanejamentoVisitasRoute
  AppPreferenciasRoute: typeof AppPreferenciasRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppRegistroCampoRoute: typeof AppRegistroCampoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRepresentantesRoute: typeof AppRepresentantesRouteWithChildren
  AppStatusRoute: typeof AppStatusRoute
  AppVendasRoute: typeof AppVendasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppRepresentanteRoute: AppAppRepresentanteRoute,
  AppAtividadesRoute: AppAtividadesRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppClientesRoute: AppClientesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIaInsightsRoute: AppIaInsightsRoute,
  AppImportacaoRoute: AppImportacaoRoute,
  AppInteligenciaRoute: AppInteligenciaRoute,
  AppMapaRoute: AppMapaRoute,
  AppMetasRoute: AppMetasRoute,
  AppOportunidadesRoute: AppOportunidadesRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppPlanejamentoRoute: AppPlanejamentoRoute,
  AppPlanejamentoVisitasRoute: AppPlanejamentoVisitasRoute,
  AppPreferenciasRoute: AppPreferenciasRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppRegistroCampoRoute: AppRegistroCampoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRepresentantesRoute: AppRepresentantesRouteWithChildren,
  AppStatusRoute: AppStatusRoute,
  AppVendasRoute: AppVendasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DiagnosticsRoute: DiagnosticsRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicHooksDailyDigestRoute: ApiPublicHooksDailyDigestRoute,
  ApiPublicHooksRunAlertsRoute: ApiPublicHooksRunAlertsRoute,
  ApiPublicHooksSendWelcomeRoute: ApiPublicHooksSendWelcomeRoute,
  ApiPublicHooksWhatsappRoute: ApiPublicHooksWhatsappRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
